version: '2'

services:
  module_string_upcase:
    image: registry.babl.sh/larskluge/string-upcase:v49
    environment:
      BABL_MODULE: larskluge/string-upcase
      BABL_MODULE_VERSION: v49
      BABL_COMMAND: /bin/app
      BABL_KAFKA_BROKERS: "kafka:9092"
      BABL_STORAGE: "storage:4443"
      BABL_DEBUG: "true"
    depends_on:
      - kafka
      - storage
    restart: always

  supervisor:
    image: registry.babl.sh/supervisor2:v71
    ports:
      - "4445:4445"
    command: "/bin/supervisor2 -kb kafka:9092 -debug -storage storage:4443"
    depends_on:
      - kafka
      - storage
    restart: always

  storage:
    image: registry.babl.sh/storage:v40
    ports:
      - "4443:4443"
      - "4442:4442"
    command: "babl-storage -cache-dir=/tmp/cache -log-format=json -file-server-address=:4442 -upload-server-address=:4443 -blob-url-template=http://storage:4442/%s"
    restart: always

  zookeeper:
    image: jplock/zookeeper:3.4.8
    volumes:
      - "./data:/tmp/zookeeper"

  kafka:
    image: wurstmeister/kafka:0.9.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_MESSAGE_MAX_BYTES: "100000000"
      KAFKA_REPLICA_FETCH_MAX_BYTES: "104857600"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "modules:1:1"
    restart: always

  test:
    build: ./test
